name: CI bzmeta-rs (wasip1)

on:
  push:
    paths:
      - 'bzmeta-rs/**'
      - '.github/workflows/bzmeta-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'bzmeta-rs/**'
      - '.github/workflows/bzmeta-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: bzmeta-rs
