name: CI comicinfo-rs (wasip1)

on:
  push:
    paths:
      - 'comicinfo-rs/**'
      - '.github/workflows/comicinfo-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'comicinfo-rs/**'
      - '.github/workflows/comicinfo-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: comicinfo-rs
