name: CI dlsitemeta-rs (wasip1)

on:
  push:
    paths:
      - 'dlsitemeta-rs/**'
      - '.github/workflows/dlsitemeta-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'dlsitemeta-rs/**'
      - '.github/workflows/dlsitemeta-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: dlsitemeta-rs
