name: CI ehdb-rs (wasip1)

on:
  push:
    paths:
      - 'ehdb-rs/**'
      - '.github/workflows/ehdb-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'ehdb-rs/**'
      - '.github/workflows/ehdb-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: ehdb-rs
