name: CI ehdl-rs (wasip1)

on:
  push:
    paths:
      - 'ehdl-rs/**'
      - '.github/workflows/ehdl-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'ehdl-rs/**'
      - '.github/workflows/ehdl-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: ehdl-rs
