name: CI ehlogin-rs (wasip1)

on:
  push:
    paths:
      - 'ehlogin-rs/**'
      - '.github/workflows/ehlogin-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'ehlogin-rs/**'
      - '.github/workflows/ehlogin-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: ehlogin-rs
