name: CI nhlogin-rs (wasip1)

on:
  push:
    paths:
      - 'nhlogin-rs/**'
      - '.github/workflows/nhlogin-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'nhlogin-rs/**'
      - '.github/workflows/nhlogin-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: nhlogin-rs
