name: CI nhsource-rs (wasip1)

on:
  push:
    paths:
      - 'nhsource-rs/**'
      - '.github/workflows/nhsource-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'nhsource-rs/**'
      - '.github/workflows/nhsource-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: nhsource-rs
