name: CI picacglogin-rs (wasip1)

on:
  push:
    paths:
      - 'picacglogin-rs/**'
      - '.github/workflows/picacglogin-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'picacglogin-rs/**'
      - '.github/workflows/picacglogin-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: picacglogin-rs
