name: CI tagmerge-rs (wasip1)

on:
  push:
    paths:
      - 'tagmerge-rs/**'
      - '.github/workflows/tagmerge-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'tagmerge-rs/**'
      - '.github/workflows/tagmerge-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: tagmerge-rs
