name: CI xdl-rs (wasip1)

on:
  push:
    paths:
      - 'xdl-rs/**'
      - '.github/workflows/xdl-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  pull_request:
    paths:
      - 'xdl-rs/**'
      - '.github/workflows/xdl-rs-wasip1.yml'
      - '.github/workflows/_build-wasip1.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-wasip1.yml
    with:
      plugin: xdl-rs
